### ISSUE TITLE
Bug when starting build

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/pdf-export-component#249]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

> @groceristar/pdf-export@1.2.0 prebuild /home/vadim/work/javascript/pdf-export-component
> npm run std --silent

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'prelude-ls'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vadim/work/javascript/pdf-export-component/node_modules/levn/lib/parse-string.js:4:12)
    at Object.<anonymous> (/home/vadim/work/javascript/pdf-export-component/node_modules/levn/lib/parse-string.js:113:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

> @groceristar/pdf-export@1.2.0 build /home/vadim/work/javascript/pdf-export-component
> rollup -c config/prod.js

Error: ENOENT: no such file or directory, lstat '/home/vadim/work/javascript/pdf-export-component/config/prod.js'
    at Object.realpathSync (fs.js:1461:7)
    at runRollup (/home/vadim/work/javascript/pdf-export-component/node_modules/rollup/bin/rollup:3929:20)
    at Object.<anonymous> (/home/vadim/work/javascript/pdf-export-component/node_modules/rollup/bin/rollup:4014:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @groceristar/pdf-export@1.2.0 build: `rollup -c config/prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @groceristar/pdf-export@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vadim/.npm/_logs/2019-06-23T20_34_48_241Z-debug.log

**Comment by atherdon** [comment]
can you try a downgraded version of this module as well? maybe it will help.

I think it because Eugene decide to build code with rollup only, without using babel at all...

**Comment by vadim9999** [comment]
FIrst error I have fixed with adding eslint second with replacing prod on product

**Comment by vadim9999** [comment]
Now I have !] (babel plugin) Error: Plugin/Preset files are not allowed to export objects, only functions. In /home/vadim/work/javascript/pdf-export-component/node_modules/babel-preset-es2015/lib/index.js
or after deleting babel-preset-es2015 It's sends error that can't find it

**Comment by atherdon** [comment]
i assume we should leave this error to Eugene. Because he started to mess with rollup. and he should finish it.

try a prev version please, because i think it'll help - because before i didn't experience this error.

Actually, this is one of the perfect example of why i fucking love this modularity approach(and i want to do it more and more). Because we can really easily to locate a source of a problem. just imagine if all fetch, backend, react were messed up in one place and when something crashing - it went down the whole project at one time
